#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2018.3 (64-bit)
#
# Filename    : elaborate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for elaborating the compiled design
#
# Generated by Vivado on Wed Oct 21 12:43:48 CDT 2020
# SW Build 2405991 on Thu Dec  6 23:36:41 MST 2018
#
# Copyright 1986-2018 Xilinx, Inc. All Rights Reserved.
#
# usage: elaborate.sh
#
# ****************************************************************************
ExecStep()
{
"$@"
RETVAL=$?
if [ $RETVAL -ne 0 ]
then
exit $RETVAL
fi
}
ExecStep xelab -wto 0bbadb2d593f42598df4aae8ffb3ec95 --incr --debug typical --relax --mt 8 --include "../../../../shell_imp.ip_user_files/bd/design_1/ip/design_1_xlconstant_0_0/sim" -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip -L xpm --snapshot cpu_ctrl_tb_behav xil_defaultlib.cpu_ctrl_tb xil_defaultlib.glbl -log elaborate.log
