# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/digilent-xdc-master/Nexys-A7-100T-Master.xdc

# Block Designs: bd/design_1/design_1.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1 || ORIG_REF_NAME==design_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_prog_mem_0_0/design_1_prog_mem_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_prog_mem_0_0 || ORIG_REF_NAME==design_1_prog_mem_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_data_mem_0_0/design_1_data_mem_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_data_mem_0_0 || ORIG_REF_NAME==design_1_data_mem_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_programmer_0_0/design_1_programmer_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_programmer_0_0 || ORIG_REF_NAME==design_1_programmer_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_uart_0_2/design_1_uart_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_uart_0_2 || ORIG_REF_NAME==design_1_uart_0_2} -quiet] -quiet

# IP: bd/design_1/ip/design_1_clk_wiz_0_0/design_1_clk_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_clk_wiz_0_0 || ORIG_REF_NAME==design_1_clk_wiz_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_and_gate_0_0/design_1_and_gate_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_and_gate_0_0 || ORIG_REF_NAME==design_1_and_gate_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_sync_extern_0_0/design_1_sync_extern_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_sync_extern_0_0 || ORIG_REF_NAME==design_1_sync_extern_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_sync_word_0_0/design_1_sync_word_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_sync_word_0_0 || ORIG_REF_NAME==design_1_sync_word_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_sync_word_1_0/design_1_sync_word_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_sync_word_1_0 || ORIG_REF_NAME==design_1_sync_word_1_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_sync_extern_0_1/design_1_sync_extern_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_sync_extern_0_1 || ORIG_REF_NAME==design_1_sync_extern_0_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_sync_extern_1_0/design_1_sync_extern_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_sync_extern_1_0 || ORIG_REF_NAME==design_1_sync_extern_1_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_sync_extern_0_2/design_1_sync_extern_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_sync_extern_0_2 || ORIG_REF_NAME==design_1_sync_extern_0_2} -quiet] -quiet

# IP: bd/design_1/ip/design_1_sync_extern_0_3/design_1_sync_extern_0_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_sync_extern_0_3 || ORIG_REF_NAME==design_1_sync_extern_0_3} -quiet] -quiet

# IP: bd/design_1/ip/design_1_shell_cpu_top_0_0/design_1_shell_cpu_top_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_shell_cpu_top_0_0 || ORIG_REF_NAME==design_1_shell_cpu_top_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_uart_controller_0_0/design_1_uart_controller_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_uart_controller_0_0 || ORIG_REF_NAME==design_1_uart_controller_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_uart_0_0/design_1_uart_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_uart_0_0 || ORIG_REF_NAME==design_1_uart_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_sync_extern_0_4/design_1_sync_extern_0_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_sync_extern_0_4 || ORIG_REF_NAME==design_1_sync_extern_0_4} -quiet] -quiet

# IP: bd/design_1/ip/design_1_sync_byte_0_0/design_1_sync_byte_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_sync_byte_0_0 || ORIG_REF_NAME==design_1_sync_byte_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_sync_extern_1_1/design_1_sync_extern_1_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_sync_extern_1_1 || ORIG_REF_NAME==design_1_sync_extern_1_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_sync_byte_1_0/design_1_sync_byte_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_sync_byte_1_0 || ORIG_REF_NAME==design_1_sync_byte_1_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_sync_extern_2_0/design_1_sync_extern_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_sync_extern_2_0 || ORIG_REF_NAME==design_1_sync_extern_2_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_display_ctrl_0_0/design_1_display_ctrl_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_display_ctrl_0_0 || ORIG_REF_NAME==design_1_display_ctrl_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_nexys_7seg_0_0/design_1_nexys_7seg_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_nexys_7seg_0_0 || ORIG_REF_NAME==design_1_nexys_7seg_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_clk_div_0_0/design_1_clk_div_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_clk_div_0_0 || ORIG_REF_NAME==design_1_clk_div_0_0} -quiet] -quiet

# XDC: bd/design_1/design_1_ooc.xdc
