# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/digilent-xdc-master/Nexys-A7-100T-Master.xdc

# Block Designs: bd/design_1/design_1.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1 || ORIG_REF_NAME==design_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_CTRL_UNIT_0_0/design_1_CTRL_UNIT_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_CTRL_UNIT_0_0 || ORIG_REF_NAME==design_1_CTRL_UNIT_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_reg_file_0_0/design_1_reg_file_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_reg_file_0_0 || ORIG_REF_NAME==design_1_reg_file_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_ALU_0_0/design_1_ALU_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_ALU_0_0 || ORIG_REF_NAME==design_1_ALU_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_prog_mem_0_0/design_1_prog_mem_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_prog_mem_0_0 || ORIG_REF_NAME==design_1_prog_mem_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_prog_cnt_reg_0_0/design_1_prog_cnt_reg_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_prog_cnt_reg_0_0 || ORIG_REF_NAME==design_1_prog_cnt_reg_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_data_mem_0_0/design_1_data_mem_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_data_mem_0_0 || ORIG_REF_NAME==design_1_data_mem_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_ALU_CTRL_0_0/design_1_ALU_CTRL_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_ALU_CTRL_0_0 || ORIG_REF_NAME==design_1_ALU_CTRL_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_reg_file_input_mux_0_0/design_1_reg_file_input_mux_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_reg_file_input_mux_0_0 || ORIG_REF_NAME==design_1_reg_file_input_mux_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_cmp_status_reg_0_0/design_1_cmp_status_reg_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_cmp_status_reg_0_0 || ORIG_REF_NAME==design_1_cmp_status_reg_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_ri_imm_ext_0_0/design_1_ri_imm_ext_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_ri_imm_ext_0_0 || ORIG_REF_NAME==design_1_ri_imm_ext_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_imm_ext_0_0/design_1_imm_ext_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_imm_ext_0_0 || ORIG_REF_NAME==design_1_imm_ext_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_adder_0_0/design_1_adder_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_adder_0_0 || ORIG_REF_NAME==design_1_adder_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_adder_1_0/design_1_adder_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_adder_1_0 || ORIG_REF_NAME==design_1_adder_1_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xlconstant_0_0/design_1_xlconstant_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xlconstant_0_0 || ORIG_REF_NAME==design_1_xlconstant_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_stack_ptr_reg_0_0/design_1_stack_ptr_reg_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_stack_ptr_reg_0_0 || ORIG_REF_NAME==design_1_stack_ptr_reg_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_ri_imm_upper_concat_0_0/design_1_ri_imm_upper_concat_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_ri_imm_upper_concat_0_0 || ORIG_REF_NAME==design_1_ri_imm_upper_concat_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_programmer_0_0/design_1_programmer_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_programmer_0_0 || ORIG_REF_NAME==design_1_programmer_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_uart_0_2/design_1_uart_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_uart_0_2 || ORIG_REF_NAME==design_1_uart_0_2} -quiet] -quiet

# IP: bd/design_1/ip/design_1_clk_wiz_0_0/design_1_clk_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_clk_wiz_0_0 || ORIG_REF_NAME==design_1_clk_wiz_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_and_gate_0_0/design_1_and_gate_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_and_gate_0_0 || ORIG_REF_NAME==design_1_and_gate_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_sync_extern_0_0/design_1_sync_extern_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_sync_extern_0_0 || ORIG_REF_NAME==design_1_sync_extern_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_sync_word_0_0/design_1_sync_word_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_sync_word_0_0 || ORIG_REF_NAME==design_1_sync_word_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_sync_word_1_0/design_1_sync_word_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_sync_word_1_0 || ORIG_REF_NAME==design_1_sync_word_1_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_sync_extern_0_1/design_1_sync_extern_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_sync_extern_0_1 || ORIG_REF_NAME==design_1_sync_extern_0_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_sync_extern_1_0/design_1_sync_extern_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_sync_extern_1_0 || ORIG_REF_NAME==design_1_sync_extern_1_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_sync_extern_0_2/design_1_sync_extern_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_sync_extern_0_2 || ORIG_REF_NAME==design_1_sync_extern_0_2} -quiet] -quiet

# IP: bd/design_1/ip/design_1_sync_extern_0_3/design_1_sync_extern_0_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_sync_extern_0_3 || ORIG_REF_NAME==design_1_sync_extern_0_3} -quiet] -quiet

# IP: bd/design_1/ip/design_1_mux_2_to_1_0_0/design_1_mux_2_to_1_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_mux_2_to_1_0_0 || ORIG_REF_NAME==design_1_mux_2_to_1_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_mux_2_to_1_1_0/design_1_mux_2_to_1_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_mux_2_to_1_1_0 || ORIG_REF_NAME==design_1_mux_2_to_1_1_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_mux_2_to_1_0_1/design_1_mux_2_to_1_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_mux_2_to_1_0_1 || ORIG_REF_NAME==design_1_mux_2_to_1_0_1} -quiet] -quiet

# XDC: bd/design_1/design_1_ooc.xdc
